export default {
	novato: {
		id: "novato",
		label: "Novato",
		headlineColor: "#645e65",
		contentColor: "#c5c5c5",
		announcementColor: "#ffffff",
	},
	iniciante: {
		id: "iniciante",
		label: "Iniciante",
		headlineColor: "#645e65",
		contentColor: "#b296b7",
		announcementColor: "#edd1fa",
	},
	regular: {
		id: "regular",
		label: "Regular",
		headlineColor: "#645e65",
		contentColor: "#d592f4",
		announcementColor: "#D592F4",
	},
	avanzado: {
		id: "avanzado",
		label: "Avanzado",
		headlineColor: "#645e65",
		contentColor: "#96298b",
		announcementColor: "#FF64FA",
	},
	veterano: {
		id: "veterano",
		label: "Veterano",
		headlineColor: "#8b2154",
		contentColor: "#ff2b91",
		announcementColor: "#DD1EE5",
	},
	sabio: {
		id: "sabio",
		label: "Sabio",
		headlineColor: "#774292",
		contentColor: "#c248ff",
		announcementColor: "#FFA464",
	},
	experto: {
		id: "experto",
		label: "Experto",
		headlineColor: "#8d804a",
		contentColor: "#fbc900",
		announcementColor: "#FFE957",
	},
	adalovelace: {
		id: "adalovelace",
		label: "Ada Lovelace",
		headlineColor: "#a34c2a",
		contentColor: "#ff6427",
		announcementColor: "#FF9747",
	},
} as Record<string, { id: string; label: string; headlineColor: string; contentColor: string; announcementColor: string }>;
